version: '3'

services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "8000:8000"

  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=8000
    volumes:
      - /dev/shm:/dev/shm